version: "3.9"

services:
  dbackup:
    build: ./source
    container_name: DBackup
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./backups:/app/backups
    labels:
      - dbackup.runner=this
    restart: unless-stopped

  postgres:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: example
    labels:
      - dbackup.on=true
      - mytool.type="postgres"
    volumes:
      - pgdata:/var/lib/postgresql/data

  sqlite:
    image: alpine
    command: ["sh", "-c", "sleep infinity"]
    labels:
      - dbackup.on=true
      - mytool.type="sqlite"
    volumes:
      - ./sqlite-data:/data

volumes:
  pgdata:
